version: '3.8'

services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: "yarn dev"

volumes:
  node_modules: {}
